# 🚀 Terraform Outputs - Generated by Sudarshan Gawande
# 💼 https://sudarshangawande.com | 🐙 https://github.com/sudarshan-gawande

output "ec2_public_ip" {
  description = "Public IP of the EC2 instance"
  value       = module.ec2.instance_public_ip
}

output "vpc_id" {
  description = "ID of the VPC created"
  value       = module.vpc.vpc_id
}

output "alb_dns" {
  description = "Application Load Balancer DNS Name"
  value       = module.alb.alb_dns
}

# 🧾 Optional: Display your project name as a output
output "project_info" {
  value = <<EOT
------------------------------------------------------
✅ AWS Infra Automated via Terraform
🔧 Author: Sudarshan Gawande
------------------------------------------------------
EOT
}
